language: python
sudo: false
python:
 - 3.6
 - "3.7-dev"
 - "nightly"

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.5
      - gcc-4.9
      - gcc-5
      - gcc-6

install:
  - pip install -q -r requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - echo "TODO"
